---
title: "Analysis"
subtitle: ""
author:
- Veronica Price-Jones
- Lien Reyserhove
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
#  pdf_document:
#    df_print: kable
#    number_sections: yes
#    toc: yes
#    toc_depth: 3
---

(short description of the goal of this document)

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries:

```{r}
library(tidyverse)      # To do data science
library(magrittr)       # To use %<>% pipes
library(here)           # To find files
library(readxl)         # To read Excel files
library(janitor)        # To clean input data
library(ordinal)
```

# Read source data

Create a data frame `input_data` from the source data:
 
```{r}
input_data <- read_excel(path = here("data", "GLMData2.xlsx")) 
```

Preview data:

```{r}
input_data %>% head(n = 5)
```

# Pre-processing

## Tidy data

```{r}
input_data %<>%
  remove_empty("rows") %>%       # Remove empty rows
  clean_names()                  # Have sensible (lowercase) column names
```

Rename variable:

```{r}
input_data <- input_data %>% rename(no_ias_records = number_of_alien_or_invasive_alien_species_records)
```

# Analysis

Define `no_ias_records` as and ordered factor:

```{r}
input_data$no_ias_records <- factor(input_data $ no_ias_records, ordered = TRUE)
```

Attempt for analysing the data:

```{r}
model <- clm(no_ias_records ~ design, data = input_data)
```
```

```{r}
```

